[project]
name = "my-project-api"          # TODO: rename
version = "0.1.0"
description = "Django + DRF REST API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
    "django-cors-headers>=4.9",
    "django-filter>=25.0",
    "djangorestframework>=3.17",
    "djangorestframework-simplejwt>=5.5",
    "psycopg2-binary>=2.9",
    "python-decouple>=3.8",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3",
    "faker>=33.0",
    "pre-commit>=4.5",
    "pytest>=8.3",
    "pytest-cov>=6.0",
    "pytest-django>=4.9",
    "ruff>=0.15",
]
prod = [
    "gunicorn>=25.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.testing"
python_files = ["test_*.py"]
addopts = "--tb=short -ra"
testpaths = ["apps"]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "migrations",
    "*.pyc",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "DJ",  # flake8-django
    "T20", # flake8-print
]
ignore = ["E501", "B008"]

[tool.ruff.lint.isort]
known-first-party = ["config", "apps"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint.per-file-ignores]
"config/settings/*.py" = ["F403", "F405"]
