# Generated by Django 6.0.6 on 2026-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Gestor'), (3, 'Cliente')], db_index=True, default=1, verbose_name='Role'),
        ),
    ]
