# Generated by Django 6.0.6 on 2026-06-23 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('tipo', models.CharField(choices=[('FISICA', 'Persona física'), ('JURIDICA', 'Persona jurídica')], max_length=10, verbose_name='tipo')),
                ('nif', models.CharField(max_length=9, unique=True, verbose_name='NIF/CIF')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellidos', models.CharField(blank=True, max_length=200, verbose_name='apellidos')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='razón social')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('calle', models.CharField(max_length=255, verbose_name='calle')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='código postal')),
                ('municipio', models.CharField(max_length=100, verbose_name='municipio')),
                ('provincia', models.CharField(max_length=100, verbose_name='provincia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='gestor')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario vinculado')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
